### ISSUE TITLE
Error when build package

### ISSUE THREAD

**Issue by zlqs1985** [floswald/ConsProb.jl#1]
After installing ConsProb.jl using `Pkg.clone()` command and then `using ConsProb`, the console show me the following error message

```
LoadError：LoadError:ArgumentError: FastGaussQuadrature not found in the path
in require at loading.ji:233
in include at boot     ji:261
in include_from_loading at loading jl:304
······

```

**Comment by floswald** [comment]
yes that means that you must install `FastGaussQuadrature`. i didn't add a `REQUIRE` file yet, so you have to install all required packages manually. sorry.
